### ISSUE TITLE
How to use this library ?

### ISSUE THREAD

**Issue by rajkosto** [GaijinEntertainment/sqrat#1]
It seems to require EASTL and other things not mentioned anywhere, I have no idea how to configure EASTL (EABase configuration?)

**Comment by AntonYudintsev** [comment]
You can also replace "eastl" with "std"

we'd better make in configurable...

**Comment by rajkosto** [comment]
Yeah thats what the fork i forked and fixed to work does, anyone wanting this now can use it i guess https://github.com/rajkosto/sqrat/commits/master

**Comment by AntonYudintsev** [comment]
Thanks.
We will try to make it configurable asap.

**Comment by AntonYudintsev** [comment]
Fixed in https://github.com/GaijinEntertainment/sqrat/pull/2
